/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDtoTests
    {
        // TODO uncomment below to declare an instance variable for BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDto
        //private BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDto
            //instance = new BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDto
        /// </summary>
        [Test]
        public void BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDto
            //Assert.IsInstanceOfType<BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDto> (instance, "variable 'instance' is a BdoServiceModelsDtoWasteRegisterElectronicWasteRecordCardUpdateKezsEquipmentGroupCardDto");
        }


        /// <summary>
        /// Test the property 'KezsEquipmentGroupCardId'
        /// </summary>
        [Test]
        public void KezsEquipmentGroupCardIdTest()
        {
            // TODO unit test for the property 'KezsEquipmentGroupCardId'
        }
        /// <summary>
        /// Test the property 'KezsEquipmentGroupCodeName'
        /// </summary>
        [Test]
        public void KezsEquipmentGroupCodeNameTest()
        {
            // TODO unit test for the property 'KezsEquipmentGroupCodeName'
        }
        /// <summary>
        /// Test the property 'StockMass'
        /// </summary>
        [Test]
        public void StockMassTest()
        {
            // TODO unit test for the property 'StockMass'
        }

    }

}
