/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponseTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponse
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponse
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponse
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponse
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponse> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWasteResponse");
        }


        /// <summary>
        /// Test the property 'KepwDismantleProducedWasteId'
        /// </summary>
        [Test]
        public void KepwDismantleProducedWasteIdTest()
        {
            // TODO unit test for the property 'KepwDismantleProducedWasteId'
        }
        /// <summary>
        /// Test the property 'KepwId'
        /// </summary>
        [Test]
        public void KepwIdTest()
        {
            // TODO unit test for the property 'KepwId'
        }
        /// <summary>
        /// Test the property 'WasteCodeId'
        /// </summary>
        [Test]
        public void WasteCodeIdTest()
        {
            // TODO unit test for the property 'WasteCodeId'
        }
        /// <summary>
        /// Test the property 'WasteCode'
        /// </summary>
        [Test]
        public void WasteCodeTest()
        {
            // TODO unit test for the property 'WasteCode'
        }
        /// <summary>
        /// Test the property 'ProductionDate'
        /// </summary>
        [Test]
        public void ProductionDateTest()
        {
            // TODO unit test for the property 'ProductionDate'
        }
        /// <summary>
        /// Test the property 'WasteMass'
        /// </summary>
        [Test]
        public void WasteMassTest()
        {
            // TODO unit test for the property 'WasteMass'
        }
        /// <summary>
        /// Test the property 'ReusablePartsMass'
        /// </summary>
        [Test]
        public void ReusablePartsMassTest()
        {
            // TODO unit test for the property 'ReusablePartsMass'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtended'
        /// </summary>
        [Test]
        public void WasteCodeExtendedTest()
        {
            // TODO unit test for the property 'WasteCodeExtended'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtendedDescription'
        /// </summary>
        [Test]
        public void WasteCodeExtendedDescriptionTest()
        {
            // TODO unit test for the property 'WasteCodeExtendedDescription'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassification'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassification'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassificationDescription'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationDescriptionTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassificationDescription'
        }
        /// <summary>
        /// Test the property 'InstallationName'
        /// </summary>
        [Test]
        public void InstallationNameTest()
        {
            // TODO unit test for the property 'InstallationName'
        }

    }

}
