/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequestTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequest
        //private WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequest
            //instance = new WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequest
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequest
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequest> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleProcessedWasteV1UpdateDismantleProcessedWasteRequest");
        }


        /// <summary>
        /// Test the property 'KepwDismantleProcessedWasteId'
        /// </summary>
        [Test]
        public void KepwDismantleProcessedWasteIdTest()
        {
            // TODO unit test for the property 'KepwDismantleProcessedWasteId'
        }
        /// <summary>
        /// Test the property 'WasteCodeId'
        /// </summary>
        [Test]
        public void WasteCodeIdTest()
        {
            // TODO unit test for the property 'WasteCodeId'
        }
        /// <summary>
        /// Test the property 'RecycledWasteMass'
        /// </summary>
        [Test]
        public void RecycledWasteMassTest()
        {
            // TODO unit test for the property 'RecycledWasteMass'
        }
        /// <summary>
        /// Test the property 'EnergyRecoveryWasteMass'
        /// </summary>
        [Test]
        public void EnergyRecoveryWasteMassTest()
        {
            // TODO unit test for the property 'EnergyRecoveryWasteMass'
        }
        /// <summary>
        /// Test the property 'OtherThanRecyclingWasteMass'
        /// </summary>
        [Test]
        public void OtherThanRecyclingWasteMassTest()
        {
            // TODO unit test for the property 'OtherThanRecyclingWasteMass'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtended'
        /// </summary>
        [Test]
        public void WasteCodeExtendedTest()
        {
            // TODO unit test for the property 'WasteCodeExtended'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtendedDescription'
        /// </summary>
        [Test]
        public void WasteCodeExtendedDescriptionTest()
        {
            // TODO unit test for the property 'WasteCodeExtendedDescription'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassification'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassification'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassificationDescription'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationDescriptionTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassificationDescription'
        }
        /// <summary>
        /// Test the property 'InstallationName'
        /// </summary>
        [Test]
        public void InstallationNameTest()
        {
            // TODO unit test for the property 'InstallationName'
        }

    }

}
