/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequestTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequest
        //private WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequest
            //instance = new WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequest
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequest
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequest> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardV1SearchKeoRequest");
        }


        /// <summary>
        /// Test the property 'WasteCode'
        /// </summary>
        [Test]
        public void WasteCodeTest()
        {
            // TODO unit test for the property 'WasteCode'
        }
        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Test]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'PaginationParameters'
        /// </summary>
        [Test]
        public void PaginationParametersTest()
        {
            // TODO unit test for the property 'PaginationParameters'
        }

    }

}
