/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponseTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponse
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponse
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponse
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponse
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponse> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1RejectKpokResponse");
        }


        /// <summary>
        /// Test the property 'CardSubtype'
        /// </summary>
        [Test]
        public void CardSubtypeTest()
        {
            // TODO unit test for the property 'CardSubtype'
        }

    }

}
