/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponseTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponse
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponse
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponse
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponse
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponse> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CheckWasteCodeUsedInKepwCreateContextResponse");
        }


        /// <summary>
        /// Test the property 'IsWasteCodeUsedInKepwCreateContext'
        /// </summary>
        [Test]
        public void IsWasteCodeUsedInKepwCreateContextTest()
        {
            // TODO unit test for the property 'IsWasteCodeUsedInKepwCreateContext'
        }

    }

}
