/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsCollectionsOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsCollectionsOrderTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsCollectionsOrder
        //private WasteRegisterPublicApiApiModelsCollectionsOrder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsCollectionsOrder
            //instance = new WasteRegisterPublicApiApiModelsCollectionsOrder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsCollectionsOrder
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsCollectionsOrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsCollectionsOrder
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsCollectionsOrder> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsCollectionsOrder");
        }


        /// <summary>
        /// Test the property 'IsAscending'
        /// </summary>
        [Test]
        public void IsAscendingTest()
        {
            // TODO unit test for the property 'IsAscending'
        }
        /// <summary>
        /// Test the property 'OrderColumn'
        /// </summary>
        [Test]
        public void OrderColumnTest()
        {
            // TODO unit test for the property 'OrderColumn'
        }

    }

}
