/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequestTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequest
        //private WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequest
            //instance = new WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequest
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequest
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequest> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardV1UpdateApprovedTransferKpokRequest");
        }


        /// <summary>
        /// Test the property 'KpokId'
        /// </summary>
        [Test]
        public void KpokIdTest()
        {
            // TODO unit test for the property 'KpokId'
        }
        /// <summary>
        /// Test the property 'CommuneId'
        /// </summary>
        [Test]
        public void CommuneIdTest()
        {
            // TODO unit test for the property 'CommuneId'
        }
        /// <summary>
        /// Test the property 'CommuneArea'
        /// </summary>
        [Test]
        public void CommuneAreaTest()
        {
            // TODO unit test for the property 'CommuneArea'
        }
        /// <summary>
        /// Test the property 'WasteCodeId'
        /// </summary>
        [Test]
        public void WasteCodeIdTest()
        {
            // TODO unit test for the property 'WasteCodeId'
        }
        /// <summary>
        /// Test the property 'WasteMass'
        /// </summary>
        [Test]
        public void WasteMassTest()
        {
            // TODO unit test for the property 'WasteMass'
        }
        /// <summary>
        /// Test the property 'VehicleRegNumber'
        /// </summary>
        [Test]
        public void VehicleRegNumberTest()
        {
            // TODO unit test for the property 'VehicleRegNumber'
        }
        /// <summary>
        /// Test the property 'PlannedTransportTime'
        /// </summary>
        [Test]
        public void PlannedTransportTimeTest()
        {
            // TODO unit test for the property 'PlannedTransportTime'
        }
        /// <summary>
        /// Test the property 'RealTransportTime'
        /// </summary>
        [Test]
        public void RealTransportTimeTest()
        {
            // TODO unit test for the property 'RealTransportTime'
        }
        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Test]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtended'
        /// </summary>
        [Test]
        public void WasteCodeExtendedTest()
        {
            // TODO unit test for the property 'WasteCodeExtended'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtendedDescription'
        /// </summary>
        [Test]
        public void WasteCodeExtendedDescriptionTest()
        {
            // TODO unit test for the property 'WasteCodeExtendedDescription'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassification'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassification'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassificationDescription'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationDescriptionTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassificationDescription'
        }

    }

}
