/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDtoTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDto
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDto
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDto
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDto
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDto> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiveConfirmedKpoDto");
        }


        /// <summary>
        /// Test the property 'KpoId'
        /// </summary>
        [Test]
        public void KpoIdTest()
        {
            // TODO unit test for the property 'KpoId'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Test]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'CardStatusId'
        /// </summary>
        [Test]
        public void CardStatusIdTest()
        {
            // TODO unit test for the property 'CardStatusId'
        }
        /// <summary>
        /// Test the property 'CardStatus'
        /// </summary>
        [Test]
        public void CardStatusTest()
        {
            // TODO unit test for the property 'CardStatus'
        }
        /// <summary>
        /// Test the property 'SenderCompanyId'
        /// </summary>
        [Test]
        public void SenderCompanyIdTest()
        {
            // TODO unit test for the property 'SenderCompanyId'
        }
        /// <summary>
        /// Test the property 'SenderEupId'
        /// </summary>
        [Test]
        public void SenderEupIdTest()
        {
            // TODO unit test for the property 'SenderEupId'
        }
        /// <summary>
        /// Test the property 'CarrierCompanyId'
        /// </summary>
        [Test]
        public void CarrierCompanyIdTest()
        {
            // TODO unit test for the property 'CarrierCompanyId'
        }
        /// <summary>
        /// Test the property 'ReceiverCompanyId'
        /// </summary>
        [Test]
        public void ReceiverCompanyIdTest()
        {
            // TODO unit test for the property 'ReceiverCompanyId'
        }
        /// <summary>
        /// Test the property 'ReceiverEupId'
        /// </summary>
        [Test]
        public void ReceiverEupIdTest()
        {
            // TODO unit test for the property 'ReceiverEupId'
        }
        /// <summary>
        /// Test the property 'WasteCodeId'
        /// </summary>
        [Test]
        public void WasteCodeIdTest()
        {
            // TODO unit test for the property 'WasteCodeId'
        }
        /// <summary>
        /// Test the property 'CorrectedWasteMass'
        /// </summary>
        [Test]
        public void CorrectedWasteMassTest()
        {
            // TODO unit test for the property 'CorrectedWasteMass'
        }
        /// <summary>
        /// Test the property 'Remarks'
        /// </summary>
        [Test]
        public void RemarksTest()
        {
            // TODO unit test for the property 'Remarks'
        }
        /// <summary>
        /// Test the property 'VehicleRegNumber'
        /// </summary>
        [Test]
        public void VehicleRegNumberTest()
        {
            // TODO unit test for the property 'VehicleRegNumber'
        }
        /// <summary>
        /// Test the property 'PlannedTransportTime'
        /// </summary>
        [Test]
        public void PlannedTransportTimeTest()
        {
            // TODO unit test for the property 'PlannedTransportTime'
        }
        /// <summary>
        /// Test the property 'WasteMass'
        /// </summary>
        [Test]
        public void WasteMassTest()
        {
            // TODO unit test for the property 'WasteMass'
        }
        /// <summary>
        /// Test the property 'CardApprovalTime'
        /// </summary>
        [Test]
        public void CardApprovalTimeTest()
        {
            // TODO unit test for the property 'CardApprovalTime'
        }
        /// <summary>
        /// Test the property 'ApprovalUser'
        /// </summary>
        [Test]
        public void ApprovalUserTest()
        {
            // TODO unit test for the property 'ApprovalUser'
        }
        /// <summary>
        /// Test the property 'RealTransportTime'
        /// </summary>
        [Test]
        public void RealTransportTimeTest()
        {
            // TODO unit test for the property 'RealTransportTime'
        }
        /// <summary>
        /// Test the property 'WasteProcessId'
        /// </summary>
        [Test]
        public void WasteProcessIdTest()
        {
            // TODO unit test for the property 'WasteProcessId'
        }
        /// <summary>
        /// Test the property 'CertificateNumberAndBoxNumbers'
        /// </summary>
        [Test]
        public void CertificateNumberAndBoxNumbersTest()
        {
            // TODO unit test for the property 'CertificateNumberAndBoxNumbers'
        }
        /// <summary>
        /// Test the property 'GeneratingConfirmationUser'
        /// </summary>
        [Test]
        public void GeneratingConfirmationUserTest()
        {
            // TODO unit test for the property 'GeneratingConfirmationUser'
        }
        /// <summary>
        /// Test the property 'GeneratingConfirmationTime'
        /// </summary>
        [Test]
        public void GeneratingConfirmationTimeTest()
        {
            // TODO unit test for the property 'GeneratingConfirmationTime'
        }
        /// <summary>
        /// Test the property 'ReceiveConfirmationUser'
        /// </summary>
        [Test]
        public void ReceiveConfirmationUserTest()
        {
            // TODO unit test for the property 'ReceiveConfirmationUser'
        }
        /// <summary>
        /// Test the property 'ReceiveConfirmationTime'
        /// </summary>
        [Test]
        public void ReceiveConfirmationTimeTest()
        {
            // TODO unit test for the property 'ReceiveConfirmationTime'
        }
        /// <summary>
        /// Test the property 'CardStatusCodeName'
        /// </summary>
        [Test]
        public void CardStatusCodeNameTest()
        {
            // TODO unit test for the property 'CardStatusCodeName'
        }
        /// <summary>
        /// Test the property 'IsRevised'
        /// </summary>
        [Test]
        public void IsRevisedTest()
        {
            // TODO unit test for the property 'IsRevised'
        }
        /// <summary>
        /// Test the property 'RevisedAt'
        /// </summary>
        [Test]
        public void RevisedAtTest()
        {
            // TODO unit test for the property 'RevisedAt'
        }
        /// <summary>
        /// Test the property 'RevisedBy'
        /// </summary>
        [Test]
        public void RevisedByTest()
        {
            // TODO unit test for the property 'RevisedBy'
        }
        /// <summary>
        /// Test the property 'RevisedWasteMass'
        /// </summary>
        [Test]
        public void RevisedWasteMassTest()
        {
            // TODO unit test for the property 'RevisedWasteMass'
        }
        /// <summary>
        /// Test the property 'RevisedWasteCodeId'
        /// </summary>
        [Test]
        public void RevisedWasteCodeIdTest()
        {
            // TODO unit test for the property 'RevisedWasteCodeId'
        }
        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Test]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtended'
        /// </summary>
        [Test]
        public void WasteCodeExtendedTest()
        {
            // TODO unit test for the property 'WasteCodeExtended'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtendedDescription'
        /// </summary>
        [Test]
        public void WasteCodeExtendedDescriptionTest()
        {
            // TODO unit test for the property 'WasteCodeExtendedDescription'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassification'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassification'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassificationDescription'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationDescriptionTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassificationDescription'
        }

    }

}
