/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponseTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse");
        }


        /// <summary>
        /// Test the property 'WasteMassExcavatedSum'
        /// </summary>
        [Test]
        public void WasteMassExcavatedSumTest()
        {
            // TODO unit test for the property 'WasteMassExcavatedSum'
        }
        /// <summary>
        /// Test the property 'KeoDto'
        /// </summary>
        [Test]
        public void KeoDtoTest()
        {
            // TODO unit test for the property 'KeoDto'
        }
        /// <summary>
        /// Test the property 'ExcavatedKeos'
        /// </summary>
        [Test]
        public void ExcavatedKeosTest()
        {
            // TODO unit test for the property 'ExcavatedKeos'
        }

    }

}
