/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequestTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest
        //private WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest
            //instance = new WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest");
        }


        /// <summary>
        /// Test the property 'KeokId'
        /// </summary>
        [Test]
        public void KeokIdTest()
        {
            // TODO unit test for the property 'KeokId'
        }
        /// <summary>
        /// Test the property 'KpokId'
        /// </summary>
        [Test]
        public void KpokIdTest()
        {
            // TODO unit test for the property 'KpokId'
        }
        /// <summary>
        /// Test the property 'ReceivedWithKpok'
        /// </summary>
        [Test]
        public void ReceivedWithKpokTest()
        {
            // TODO unit test for the property 'ReceivedWithKpok'
        }
        /// <summary>
        /// Test the property 'ReceivedWasteMass'
        /// </summary>
        [Test]
        public void ReceivedWasteMassTest()
        {
            // TODO unit test for the property 'ReceivedWasteMass'
        }
        /// <summary>
        /// Test the property 'ReceiveDate'
        /// </summary>
        [Test]
        public void ReceiveDateTest()
        {
            // TODO unit test for the property 'ReceiveDate'
        }
        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Test]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
        /// <summary>
        /// Test the property 'InstallationName'
        /// </summary>
        [Test]
        public void InstallationNameTest()
        {
            // TODO unit test for the property 'InstallationName'
        }

    }

}
