/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponseTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponse
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponse
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponse
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponse
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponse> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1CreateKeokReceivedResponse");
        }


        /// <summary>
        /// Test the property 'KeokReceivedId'
        /// </summary>
        [Test]
        public void KeokReceivedIdTest()
        {
            // TODO unit test for the property 'KeokReceivedId'
        }

    }

}
