/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItemTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItem
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItem
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItem
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItem
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItem> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1KeokCollectedFromRealEstateOwnerListItem");
        }


        /// <summary>
        /// Test the property 'KeokCollectedFromRealEstateOwnerId'
        /// </summary>
        [Test]
        public void KeokCollectedFromRealEstateOwnerIdTest()
        {
            // TODO unit test for the property 'KeokCollectedFromRealEstateOwnerId'
        }
        /// <summary>
        /// Test the property 'ReceiveDate'
        /// </summary>
        [Test]
        public void ReceiveDateTest()
        {
            // TODO unit test for the property 'ReceiveDate'
        }
        /// <summary>
        /// Test the property 'KpokCardNumber'
        /// </summary>
        [Test]
        public void KpokCardNumberTest()
        {
            // TODO unit test for the property 'KpokCardNumber'
        }
        /// <summary>
        /// Test the property 'ReceivedWasteMass'
        /// </summary>
        [Test]
        public void ReceivedWasteMassTest()
        {
            // TODO unit test for the property 'ReceivedWasteMass'
        }
        /// <summary>
        /// Test the property 'CreatedByUser'
        /// </summary>
        [Test]
        public void CreatedByUserTest()
        {
            // TODO unit test for the property 'CreatedByUser'
        }

    }

}
