/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItemTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItem
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItem
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItem
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItem
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItem> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoCollectedListItem");
        }


        /// <summary>
        /// Test the property 'KeoCollectedId'
        /// </summary>
        [Test]
        public void KeoCollectedIdTest()
        {
            // TODO unit test for the property 'KeoCollectedId'
        }
        /// <summary>
        /// Test the property 'CreatedByUser'
        /// </summary>
        [Test]
        public void CreatedByUserTest()
        {
            // TODO unit test for the property 'CreatedByUser'
        }
        /// <summary>
        /// Test the property 'CollectedDate'
        /// </summary>
        [Test]
        public void CollectedDateTest()
        {
            // TODO unit test for the property 'CollectedDate'
        }
        /// <summary>
        /// Test the property 'IsEntryBasedOnKpo'
        /// </summary>
        [Test]
        public void IsEntryBasedOnKpoTest()
        {
            // TODO unit test for the property 'IsEntryBasedOnKpo'
        }
        /// <summary>
        /// Test the property 'IsImportToRp'
        /// </summary>
        [Test]
        public void IsImportToRpTest()
        {
            // TODO unit test for the property 'IsImportToRp'
        }
        /// <summary>
        /// Test the property 'IsEquipmentOwnerExemptFromRecord'
        /// </summary>
        [Test]
        public void IsEquipmentOwnerExemptFromRecordTest()
        {
            // TODO unit test for the property 'IsEquipmentOwnerExemptFromRecord'
        }
        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Test]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'CollectedMass'
        /// </summary>
        [Test]
        public void CollectedMassTest()
        {
            // TODO unit test for the property 'CollectedMass'
        }
        /// <summary>
        /// Test the property 'InstallationName'
        /// </summary>
        [Test]
        public void InstallationNameTest()
        {
            // TODO unit test for the property 'InstallationName'
        }

    }

}
