/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequestTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequest
        //private WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequest
            //instance = new WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequest
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequest
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequest> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchKpokAsSenderRequest");
        }


        /// <summary>
        /// Test the property 'PaginationParameters'
        /// </summary>
        [Test]
        public void PaginationParametersTest()
        {
            // TODO unit test for the property 'PaginationParameters'
        }
        /// <summary>
        /// Test the property 'SearchInCarriers'
        /// </summary>
        [Test]
        public void SearchInCarriersTest()
        {
            // TODO unit test for the property 'SearchInCarriers'
        }
        /// <summary>
        /// Test the property 'SearchInReceivers'
        /// </summary>
        [Test]
        public void SearchInReceiversTest()
        {
            // TODO unit test for the property 'SearchInReceivers'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Locality'
        /// </summary>
        [Test]
        public void LocalityTest()
        {
            // TODO unit test for the property 'Locality'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'Nip'
        /// </summary>
        [Test]
        public void NipTest()
        {
            // TODO unit test for the property 'Nip'
        }
        /// <summary>
        /// Test the property 'IdentificationNumber'
        /// </summary>
        [Test]
        public void IdentificationNumberTest()
        {
            // TODO unit test for the property 'IdentificationNumber'
        }
        /// <summary>
        /// Test the property 'WasteCodeAndDescription'
        /// </summary>
        [Test]
        public void WasteCodeAndDescriptionTest()
        {
            // TODO unit test for the property 'WasteCodeAndDescription'
        }
        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Test]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'CardStatusCodeNames'
        /// </summary>
        [Test]
        public void CardStatusCodeNamesTest()
        {
            // TODO unit test for the property 'CardStatusCodeNames'
        }
        /// <summary>
        /// Test the property 'CommuneName'
        /// </summary>
        [Test]
        public void CommuneNameTest()
        {
            // TODO unit test for the property 'CommuneName'
        }
        /// <summary>
        /// Test the property 'CommuneArea'
        /// </summary>
        [Test]
        public void CommuneAreaTest()
        {
            // TODO unit test for the property 'CommuneArea'
        }
        /// <summary>
        /// Test the property 'CardSubtype'
        /// </summary>
        [Test]
        public void CardSubtypeTest()
        {
            // TODO unit test for the property 'CardSubtype'
        }
        /// <summary>
        /// Test the property 'TransportTime'
        /// </summary>
        [Test]
        public void TransportTimeTest()
        {
            // TODO unit test for the property 'TransportTime'
        }
        /// <summary>
        /// Test the property 'ReceiveConfirmationTime'
        /// </summary>
        [Test]
        public void ReceiveConfirmationTimeTest()
        {
            // TODO unit test for the property 'ReceiveConfirmationTime'
        }
        /// <summary>
        /// Test the property 'SenderFirstNameAndLastName'
        /// </summary>
        [Test]
        public void SenderFirstNameAndLastNameTest()
        {
            // TODO unit test for the property 'SenderFirstNameAndLastName'
        }
        /// <summary>
        /// Test the property 'ReceiverFirstNameAndLastName'
        /// </summary>
        [Test]
        public void ReceiverFirstNameAndLastNameTest()
        {
            // TODO unit test for the property 'ReceiverFirstNameAndLastName'
        }
        /// <summary>
        /// Test the property 'VehicleRegNumber'
        /// </summary>
        [Test]
        public void VehicleRegNumberTest()
        {
            // TODO unit test for the property 'VehicleRegNumber'
        }
        /// <summary>
        /// Test the property 'TransportDateRange'
        /// </summary>
        [Test]
        public void TransportDateRangeTest()
        {
            // TODO unit test for the property 'TransportDateRange'
        }
        /// <summary>
        /// Test the property 'TransportDateFrom'
        /// </summary>
        [Test]
        public void TransportDateFromTest()
        {
            // TODO unit test for the property 'TransportDateFrom'
        }
        /// <summary>
        /// Test the property 'TransportDateTo'
        /// </summary>
        [Test]
        public void TransportDateToTest()
        {
            // TODO unit test for the property 'TransportDateTo'
        }
        /// <summary>
        /// Test the property 'ReceiveConfirmationDateRange'
        /// </summary>
        [Test]
        public void ReceiveConfirmationDateRangeTest()
        {
            // TODO unit test for the property 'ReceiveConfirmationDateRange'
        }
        /// <summary>
        /// Test the property 'ReceiveConfirmationDateFrom'
        /// </summary>
        [Test]
        public void ReceiveConfirmationDateFromTest()
        {
            // TODO unit test for the property 'ReceiveConfirmationDateFrom'
        }
        /// <summary>
        /// Test the property 'ReceiveConfirmationDateTo'
        /// </summary>
        [Test]
        public void ReceiveConfirmationDateToTest()
        {
            // TODO unit test for the property 'ReceiveConfirmationDateTo'
        }

    }

}
