/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDtoTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDto
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDto
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDto
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDto
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDto> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosResearchCardListItemDto");
        }


        /// <summary>
        /// Test the property 'KekosResearchCardId'
        /// </summary>
        [Test]
        public void KekosResearchCardIdTest()
        {
            // TODO unit test for the property 'KekosResearchCardId'
        }
        /// <summary>
        /// Test the property 'BatchOfGeneratedSedimentId'
        /// </summary>
        [Test]
        public void BatchOfGeneratedSedimentIdTest()
        {
            // TODO unit test for the property 'BatchOfGeneratedSedimentId'
        }
        /// <summary>
        /// Test the property 'ResearchNumber'
        /// </summary>
        [Test]
        public void ResearchNumberTest()
        {
            // TODO unit test for the property 'ResearchNumber'
        }
        /// <summary>
        /// Test the property 'ResearchDate'
        /// </summary>
        [Test]
        public void ResearchDateTest()
        {
            // TODO unit test for the property 'ResearchDate'
        }
        /// <summary>
        /// Test the property 'PhReaction'
        /// </summary>
        [Test]
        public void PhReactionTest()
        {
            // TODO unit test for the property 'PhReaction'
        }
        /// <summary>
        /// Test the property 'DryMatterContent'
        /// </summary>
        [Test]
        public void DryMatterContentTest()
        {
            // TODO unit test for the property 'DryMatterContent'
        }
        /// <summary>
        /// Test the property 'ContentOfOrganicSubstances'
        /// </summary>
        [Test]
        public void ContentOfOrganicSubstancesTest()
        {
            // TODO unit test for the property 'ContentOfOrganicSubstances'
        }
        /// <summary>
        /// Test the property 'ContentOfAmmoniumNitrogen'
        /// </summary>
        [Test]
        public void ContentOfAmmoniumNitrogenTest()
        {
            // TODO unit test for the property 'ContentOfAmmoniumNitrogen'
        }
        /// <summary>
        /// Test the property 'ContentOfTotalNitrogen'
        /// </summary>
        [Test]
        public void ContentOfTotalNitrogenTest()
        {
            // TODO unit test for the property 'ContentOfTotalNitrogen'
        }
        /// <summary>
        /// Test the property 'ContentOfTotalPhosphorus'
        /// </summary>
        [Test]
        public void ContentOfTotalPhosphorusTest()
        {
            // TODO unit test for the property 'ContentOfTotalPhosphorus'
        }
        /// <summary>
        /// Test the property 'CalciumContent'
        /// </summary>
        [Test]
        public void CalciumContentTest()
        {
            // TODO unit test for the property 'CalciumContent'
        }
        /// <summary>
        /// Test the property 'MagnesiumContent'
        /// </summary>
        [Test]
        public void MagnesiumContentTest()
        {
            // TODO unit test for the property 'MagnesiumContent'
        }
        /// <summary>
        /// Test the property 'NumberOfParasiticEggs'
        /// </summary>
        [Test]
        public void NumberOfParasiticEggsTest()
        {
            // TODO unit test for the property 'NumberOfParasiticEggs'
        }
        /// <summary>
        /// Test the property 'SalmonellaBacteria'
        /// </summary>
        [Test]
        public void SalmonellaBacteriaTest()
        {
            // TODO unit test for the property 'SalmonellaBacteria'
        }
        /// <summary>
        /// Test the property 'CadmiumContent'
        /// </summary>
        [Test]
        public void CadmiumContentTest()
        {
            // TODO unit test for the property 'CadmiumContent'
        }
        /// <summary>
        /// Test the property 'CopperContent'
        /// </summary>
        [Test]
        public void CopperContentTest()
        {
            // TODO unit test for the property 'CopperContent'
        }
        /// <summary>
        /// Test the property 'LeadContent'
        /// </summary>
        [Test]
        public void LeadContentTest()
        {
            // TODO unit test for the property 'LeadContent'
        }
        /// <summary>
        /// Test the property 'MercuryContent'
        /// </summary>
        [Test]
        public void MercuryContentTest()
        {
            // TODO unit test for the property 'MercuryContent'
        }
        /// <summary>
        /// Test the property 'NickelContent'
        /// </summary>
        [Test]
        public void NickelContentTest()
        {
            // TODO unit test for the property 'NickelContent'
        }
        /// <summary>
        /// Test the property 'ChromeContent'
        /// </summary>
        [Test]
        public void ChromeContentTest()
        {
            // TODO unit test for the property 'ChromeContent'
        }
        /// <summary>
        /// Test the property 'ZincContent'
        /// </summary>
        [Test]
        public void ZincContentTest()
        {
            // TODO unit test for the property 'ZincContent'
        }
        /// <summary>
        /// Test the property 'IsSewageSludgeFormLiquid'
        /// </summary>
        [Test]
        public void IsSewageSludgeFormLiquidTest()
        {
            // TODO unit test for the property 'IsSewageSludgeFormLiquid'
        }
        /// <summary>
        /// Test the property 'IsSewageSludgeFormMazist'
        /// </summary>
        [Test]
        public void IsSewageSludgeFormMazistTest()
        {
            // TODO unit test for the property 'IsSewageSludgeFormMazist'
        }
        /// <summary>
        /// Test the property 'IsSewageSludgeFormEarthy'
        /// </summary>
        [Test]
        public void IsSewageSludgeFormEarthyTest()
        {
            // TODO unit test for the property 'IsSewageSludgeFormEarthy'
        }
        /// <summary>
        /// Test the property 'CanBeEdited'
        /// </summary>
        [Test]
        public void CanBeEditedTest()
        {
            // TODO unit test for the property 'CanBeEdited'
        }

    }

}
