/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequestTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequest
        //private WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequest
            //instance = new WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequest
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequest
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequest> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteProcessV1SearchWasteProcessRequest");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CodeName'
        /// </summary>
        [Test]
        public void CodeNameTest()
        {
            // TODO unit test for the property 'CodeName'
        }

    }

}
