/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponseTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse");
        }


        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Test]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'CalendarYear'
        /// </summary>
        [Test]
        public void CalendarYearTest()
        {
            // TODO unit test for the property 'CalendarYear'
        }
        /// <summary>
        /// Test the property 'WasteCodeWithDescription'
        /// </summary>
        [Test]
        public void WasteCodeWithDescriptionTest()
        {
            // TODO unit test for the property 'WasteCodeWithDescription'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CompanyAdress'
        /// </summary>
        [Test]
        public void CompanyAdressTest()
        {
            // TODO unit test for the property 'CompanyAdress'
        }
        /// <summary>
        /// Test the property 'CompanyIdentificationNumber'
        /// </summary>
        [Test]
        public void CompanyIdentificationNumberTest()
        {
            // TODO unit test for the property 'CompanyIdentificationNumber'
        }
        /// <summary>
        /// Test the property 'CompanyNip'
        /// </summary>
        [Test]
        public void CompanyNipTest()
        {
            // TODO unit test for the property 'CompanyNip'
        }
        /// <summary>
        /// Test the property 'CompanyNipEu'
        /// </summary>
        [Test]
        public void CompanyNipEuTest()
        {
            // TODO unit test for the property 'CompanyNipEu'
        }
        /// <summary>
        /// Test the property 'EupName'
        /// </summary>
        [Test]
        public void EupNameTest()
        {
            // TODO unit test for the property 'EupName'
        }
        /// <summary>
        /// Test the property 'EupIdentificationNumber'
        /// </summary>
        [Test]
        public void EupIdentificationNumberTest()
        {
            // TODO unit test for the property 'EupIdentificationNumber'
        }
        /// <summary>
        /// Test the property 'EupAdress'
        /// </summary>
        [Test]
        public void EupAdressTest()
        {
            // TODO unit test for the property 'EupAdress'
        }
        /// <summary>
        /// Test the property 'SludgeMassMgSum'
        /// </summary>
        [Test]
        public void SludgeMassMgSumTest()
        {
            // TODO unit test for the property 'SludgeMassMgSum'
        }
        /// <summary>
        /// Test the property 'SludgeMassMgSmSum'
        /// </summary>
        [Test]
        public void SludgeMassMgSmSumTest()
        {
            // TODO unit test for the property 'SludgeMassMgSmSum'
        }
        /// <summary>
        /// Test the property 'AppliedSludgeMassSum'
        /// </summary>
        [Test]
        public void AppliedSludgeMassSumTest()
        {
            // TODO unit test for the property 'AppliedSludgeMassSum'
        }
        /// <summary>
        /// Test the property 'AppliedSludgeDryMatterMassSum'
        /// </summary>
        [Test]
        public void AppliedSludgeDryMatterMassSumTest()
        {
            // TODO unit test for the property 'AppliedSludgeDryMatterMassSum'
        }
        /// <summary>
        /// Test the property 'ListItems'
        /// </summary>
        [Test]
        public void ListItemsTest()
        {
            // TODO unit test for the property 'ListItems'
        }

    }

}
