/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastesTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastes
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastes
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastes
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastes
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastes> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1KepwWithDismantleInitialWastes");
        }


        /// <summary>
        /// Test the property 'KepwId'
        /// </summary>
        [Test]
        public void KepwIdTest()
        {
            // TODO unit test for the property 'KepwId'
        }
        /// <summary>
        /// Test the property 'WasteCodeId'
        /// </summary>
        [Test]
        public void WasteCodeIdTest()
        {
            // TODO unit test for the property 'WasteCodeId'
        }
        /// <summary>
        /// Test the property 'WasteCode'
        /// </summary>
        [Test]
        public void WasteCodeTest()
        {
            // TODO unit test for the property 'WasteCode'
        }
        /// <summary>
        /// Test the property 'IsDismantle'
        /// </summary>
        [Test]
        public void IsDismantleTest()
        {
            // TODO unit test for the property 'IsDismantle'
        }
        /// <summary>
        /// Test the property 'InitialVehiclesMass'
        /// </summary>
        [Test]
        public void InitialVehiclesMassTest()
        {
            // TODO unit test for the property 'InitialVehiclesMass'
        }
        /// <summary>
        /// Test the property 'InitialVehiclesCount'
        /// </summary>
        [Test]
        public void InitialVehiclesCountTest()
        {
            // TODO unit test for the property 'InitialVehiclesCount'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtended'
        /// </summary>
        [Test]
        public void WasteCodeExtendedTest()
        {
            // TODO unit test for the property 'WasteCodeExtended'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtendedDescription'
        /// </summary>
        [Test]
        public void WasteCodeExtendedDescriptionTest()
        {
            // TODO unit test for the property 'WasteCodeExtendedDescription'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassification'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassification'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassificationDescription'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationDescriptionTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassificationDescription'
        }
        /// <summary>
        /// Test the property 'DismantleInitialWastes'
        /// </summary>
        [Test]
        public void DismantleInitialWastesTest()
        {
            // TODO unit test for the property 'DismantleInitialWastes'
        }

    }

}
