/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequestTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequest
        //private WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequest
            //instance = new WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequest
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequest
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequest> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1SearchKeokReceivedRequest");
        }


        /// <summary>
        /// Test the property 'KeokId'
        /// </summary>
        [Test]
        public void KeokIdTest()
        {
            // TODO unit test for the property 'KeokId'
        }
        /// <summary>
        /// Test the property 'PaginationParameters'
        /// </summary>
        [Test]
        public void PaginationParametersTest()
        {
            // TODO unit test for the property 'PaginationParameters'
        }

    }

}
