/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponseTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponse
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponse
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponse
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponse
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponse> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosSummaryResponse");
        }


        /// <summary>
        /// Test the property 'WasteCodeId'
        /// </summary>
        [Test]
        public void WasteCodeIdTest()
        {
            // TODO unit test for the property 'WasteCodeId'
        }
        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Test]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'InitialMass'
        /// </summary>
        [Test]
        public void InitialMassTest()
        {
            // TODO unit test for the property 'InitialMass'
        }
        /// <summary>
        /// Test the property 'InitialDryMatterMass'
        /// </summary>
        [Test]
        public void InitialDryMatterMassTest()
        {
            // TODO unit test for the property 'InitialDryMatterMass'
        }
        /// <summary>
        /// Test the property 'AppliedSedimentsSludgeMass'
        /// </summary>
        [Test]
        public void AppliedSedimentsSludgeMassTest()
        {
            // TODO unit test for the property 'AppliedSedimentsSludgeMass'
        }
        /// <summary>
        /// Test the property 'AppliedSedimentsSludgeMassDryMatter'
        /// </summary>
        [Test]
        public void AppliedSedimentsSludgeMassDryMatterTest()
        {
            // TODO unit test for the property 'AppliedSedimentsSludgeMassDryMatter'
        }
        /// <summary>
        /// Test the property 'BatchOfGeneratedSedimentsSludgeMass'
        /// </summary>
        [Test]
        public void BatchOfGeneratedSedimentsSludgeMassTest()
        {
            // TODO unit test for the property 'BatchOfGeneratedSedimentsSludgeMass'
        }
        /// <summary>
        /// Test the property 'BatchOfGeneratedSedimentsSludgeMassDryMatter'
        /// </summary>
        [Test]
        public void BatchOfGeneratedSedimentsSludgeMassDryMatterTest()
        {
            // TODO unit test for the property 'BatchOfGeneratedSedimentsSludgeMassDryMatter'
        }

    }

}
