/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDtoTests
    {
        // TODO uncomment below to declare an instance variable for WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDto
        //private WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDto
            //instance = new WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDto
        /// </summary>
        [Test]
        public void WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDto
            //Assert.IsInstanceOfType<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDto> (instance, "variable 'instance' is a WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1PlannedKpoDto");
        }


        /// <summary>
        /// Test the property 'KpoId'
        /// </summary>
        [Test]
        public void KpoIdTest()
        {
            // TODO unit test for the property 'KpoId'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Test]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'CardStatusId'
        /// </summary>
        [Test]
        public void CardStatusIdTest()
        {
            // TODO unit test for the property 'CardStatusId'
        }
        /// <summary>
        /// Test the property 'CardStatus'
        /// </summary>
        [Test]
        public void CardStatusTest()
        {
            // TODO unit test for the property 'CardStatus'
        }
        /// <summary>
        /// Test the property 'SenderCompanyId'
        /// </summary>
        [Test]
        public void SenderCompanyIdTest()
        {
            // TODO unit test for the property 'SenderCompanyId'
        }
        /// <summary>
        /// Test the property 'SenderEupId'
        /// </summary>
        [Test]
        public void SenderEupIdTest()
        {
            // TODO unit test for the property 'SenderEupId'
        }
        /// <summary>
        /// Test the property 'CarrierCompanyId'
        /// </summary>
        [Test]
        public void CarrierCompanyIdTest()
        {
            // TODO unit test for the property 'CarrierCompanyId'
        }
        /// <summary>
        /// Test the property 'ReceiverCompanyId'
        /// </summary>
        [Test]
        public void ReceiverCompanyIdTest()
        {
            // TODO unit test for the property 'ReceiverCompanyId'
        }
        /// <summary>
        /// Test the property 'ReceiverEupId'
        /// </summary>
        [Test]
        public void ReceiverEupIdTest()
        {
            // TODO unit test for the property 'ReceiverEupId'
        }
        /// <summary>
        /// Test the property 'WasteCodeId'
        /// </summary>
        [Test]
        public void WasteCodeIdTest()
        {
            // TODO unit test for the property 'WasteCodeId'
        }
        /// <summary>
        /// Test the property 'VehicleRegNumber'
        /// </summary>
        [Test]
        public void VehicleRegNumberTest()
        {
            // TODO unit test for the property 'VehicleRegNumber'
        }
        /// <summary>
        /// Test the property 'WasteMass'
        /// </summary>
        [Test]
        public void WasteMassTest()
        {
            // TODO unit test for the property 'WasteMass'
        }
        /// <summary>
        /// Test the property 'PlannedTransportTime'
        /// </summary>
        [Test]
        public void PlannedTransportTimeTest()
        {
            // TODO unit test for the property 'PlannedTransportTime'
        }
        /// <summary>
        /// Test the property 'WasteProcessId'
        /// </summary>
        [Test]
        public void WasteProcessIdTest()
        {
            // TODO unit test for the property 'WasteProcessId'
        }
        /// <summary>
        /// Test the property 'CertificateNumberAndBoxNumbers'
        /// </summary>
        [Test]
        public void CertificateNumberAndBoxNumbersTest()
        {
            // TODO unit test for the property 'CertificateNumberAndBoxNumbers'
        }
        /// <summary>
        /// Test the property 'CardStatusCodeName'
        /// </summary>
        [Test]
        public void CardStatusCodeNameTest()
        {
            // TODO unit test for the property 'CardStatusCodeName'
        }
        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Test]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtended'
        /// </summary>
        [Test]
        public void WasteCodeExtendedTest()
        {
            // TODO unit test for the property 'WasteCodeExtended'
        }
        /// <summary>
        /// Test the property 'WasteCodeExtendedDescription'
        /// </summary>
        [Test]
        public void WasteCodeExtendedDescriptionTest()
        {
            // TODO unit test for the property 'WasteCodeExtendedDescription'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassification'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassification'
        }
        /// <summary>
        /// Test the property 'HazardousWasteReclassificationDescription'
        /// </summary>
        [Test]
        public void HazardousWasteReclassificationDescriptionTest()
        {
            // TODO unit test for the property 'HazardousWasteReclassificationDescription'
        }

    }

}
