/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters
    /// </summary>
    [DataContract]
    public partial class WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters :  IEquatable<WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters" /> class.
        /// </summary>
        /// <param name="order">Ustawienia sortowania wyników.</param>
        /// <param name="page">Ustawienia strony z wynikami.</param>
        public WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters(WasteRegisterPublicApiApiModelsRequestsAuthV1Aorder order = default(WasteRegisterPublicApiApiModelsRequestsAuthV1Aorder), WasteRegisterPublicApiApiModelsRequestsAuthV1Apage page = default(WasteRegisterPublicApiApiModelsRequestsAuthV1Apage))
        {
            this.Order = order;
            this.Page = page;
        }
        
        /// <summary>
        /// Ustawienia sortowania wyników
        /// </summary>
        /// <value>Ustawienia sortowania wyników</value>
        [DataMember(Name="order", EmitDefaultValue=false)]
        public WasteRegisterPublicApiApiModelsRequestsAuthV1Aorder Order { get; set; }

        /// <summary>
        /// Ustawienia strony z wynikami
        /// </summary>
        /// <value>Ustawienia strony z wynikami</value>
        [DataMember(Name="page", EmitDefaultValue=false)]
        public WasteRegisterPublicApiApiModelsRequestsAuthV1Apage Page { get; set; }

        /// <summary>
        /// Identyfikator kolumny, według której ma być zrelizowane sortowanie
        /// </summary>
        /// <value>Identyfikator kolumny, według której ma być zrelizowane sortowanie</value>
        [DataMember(Name="getOrderColumn", EmitDefaultValue=false)]
        public string GetOrderColumn { get; private set; }

        /// <summary>
        /// Kierunek sortowania
        /// </summary>
        /// <value>Kierunek sortowania</value>
        [DataMember(Name="getOrderDirection", EmitDefaultValue=false)]
        public string GetOrderDirection { get; private set; }

        /// <summary>
        /// Sortowanie
        /// </summary>
        /// <value>Sortowanie</value>
        [DataMember(Name="getOrdering", EmitDefaultValue=false)]
        public string GetOrdering { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters {\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  GetOrderColumn: ").Append(GetOrderColumn).Append("\n");
            sb.Append("  GetOrderDirection: ").Append(GetOrderDirection).Append("\n");
            sb.Append("  GetOrdering: ").Append(GetOrdering).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters);
        }

        /// <summary>
        /// Returns true if WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters instances are equal
        /// </summary>
        /// <param name="input">Instance of WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WasteRegisterPublicApiApiModelsRequestsAuthV1AuthPaginationParameters input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Order == input.Order ||
                    (this.Order != null &&
                    this.Order.Equals(input.Order))
                ) && 
                (
                    this.Page == input.Page ||
                    (this.Page != null &&
                    this.Page.Equals(input.Page))
                ) && 
                (
                    this.GetOrderColumn == input.GetOrderColumn ||
                    (this.GetOrderColumn != null &&
                    this.GetOrderColumn.Equals(input.GetOrderColumn))
                ) && 
                (
                    this.GetOrderDirection == input.GetOrderDirection ||
                    (this.GetOrderDirection != null &&
                    this.GetOrderDirection.Equals(input.GetOrderDirection))
                ) && 
                (
                    this.GetOrdering == input.GetOrdering ||
                    (this.GetOrdering != null &&
                    this.GetOrdering.Equals(input.GetOrdering))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Order != null)
                    hashCode = hashCode * 59 + this.Order.GetHashCode();
                if (this.Page != null)
                    hashCode = hashCode * 59 + this.Page.GetHashCode();
                if (this.GetOrderColumn != null)
                    hashCode = hashCode * 59 + this.GetOrderColumn.GetHashCode();
                if (this.GetOrderDirection != null)
                    hashCode = hashCode * 59 + this.GetOrderDirection.GetHashCode();
                if (this.GetOrdering != null)
                    hashCode = hashCode * 59 + this.GetOrdering.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
