/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse
    /// </summary>
    [DataContract]
    public partial class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse :  IEquatable<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse" /> class.
        /// </summary>
        /// <param name="wasteMassServicesSum">Łączna masa wytworzonych odpadów w wyniku świadczenia usług i/lub działalności w zakresie obiektów liniowych.</param>
        /// <param name="wasteMassSum">Łączna masa wytworzonych odpadów [Mg].</param>
        /// <param name="keoDto">Karta keo.</param>
        /// <param name="generatedKeos">generatedKeos.</param>
        public WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse(double? wasteMassServicesSum = default(double?), double? wasteMassSum = default(double?), WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoDto keoDto = default(WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoDto), WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1PaginatedPageKeoGeneratedListItem generatedKeos = default(WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1PaginatedPageKeoGeneratedListItem))
        {
            this.WasteMassServicesSum = wasteMassServicesSum;
            this.WasteMassSum = wasteMassSum;
            this.KeoDto = keoDto;
            this.GeneratedKeos = generatedKeos;
        }
        
        /// <summary>
        /// Łączna masa wytworzonych odpadów w wyniku świadczenia usług i/lub działalności w zakresie obiektów liniowych
        /// </summary>
        /// <value>Łączna masa wytworzonych odpadów w wyniku świadczenia usług i/lub działalności w zakresie obiektów liniowych</value>
        [DataMember(Name="wasteMassServicesSum", EmitDefaultValue=false)]
        public double? WasteMassServicesSum { get; set; }

        /// <summary>
        /// Łączna masa wytworzonych odpadów [Mg]
        /// </summary>
        /// <value>Łączna masa wytworzonych odpadów [Mg]</value>
        [DataMember(Name="wasteMassSum", EmitDefaultValue=false)]
        public double? WasteMassSum { get; set; }

        /// <summary>
        /// Karta keo
        /// </summary>
        /// <value>Karta keo</value>
        [DataMember(Name="keoDto", EmitDefaultValue=false)]
        public WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoDto KeoDto { get; set; }

        /// <summary>
        /// Gets or Sets GeneratedKeos
        /// </summary>
        [DataMember(Name="generatedKeos", EmitDefaultValue=false)]
        public WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1PaginatedPageKeoGeneratedListItem GeneratedKeos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse {\n");
            sb.Append("  WasteMassServicesSum: ").Append(WasteMassServicesSum).Append("\n");
            sb.Append("  WasteMassSum: ").Append(WasteMassSum).Append("\n");
            sb.Append("  KeoDto: ").Append(KeoDto).Append("\n");
            sb.Append("  GeneratedKeos: ").Append(GeneratedKeos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse);
        }

        /// <summary>
        /// Returns true if WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoGeneratedResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.WasteMassServicesSum == input.WasteMassServicesSum ||
                    (this.WasteMassServicesSum != null &&
                    this.WasteMassServicesSum.Equals(input.WasteMassServicesSum))
                ) && 
                (
                    this.WasteMassSum == input.WasteMassSum ||
                    (this.WasteMassSum != null &&
                    this.WasteMassSum.Equals(input.WasteMassSum))
                ) && 
                (
                    this.KeoDto == input.KeoDto ||
                    (this.KeoDto != null &&
                    this.KeoDto.Equals(input.KeoDto))
                ) && 
                (
                    this.GeneratedKeos == input.GeneratedKeos ||
                    (this.GeneratedKeos != null &&
                    this.GeneratedKeos.Equals(input.GeneratedKeos))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WasteMassServicesSum != null)
                    hashCode = hashCode * 59 + this.WasteMassServicesSum.GetHashCode();
                if (this.WasteMassSum != null)
                    hashCode = hashCode * 59 + this.WasteMassSum.GetHashCode();
                if (this.KeoDto != null)
                    hashCode = hashCode * 59 + this.KeoDto.GetHashCode();
                if (this.GeneratedKeos != null)
                    hashCode = hashCode * 59 + this.GeneratedKeos.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
