/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse
    /// </summary>
    [DataContract]
    public partial class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse :  IEquatable<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse" /> class.
        /// </summary>
        /// <param name="wasteMassExcavatedSum">Łączna masa odpadów wydobytych ze składowiska [Mg].</param>
        /// <param name="keoDto">Karta keo.</param>
        /// <param name="excavatedKeos">excavatedKeos.</param>
        public WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse(double? wasteMassExcavatedSum = default(double?), WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoDto keoDto = default(WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoDto), WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1PaginatedPageKeoExcavatedListItem excavatedKeos = default(WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1PaginatedPageKeoExcavatedListItem))
        {
            this.WasteMassExcavatedSum = wasteMassExcavatedSum;
            this.KeoDto = keoDto;
            this.ExcavatedKeos = excavatedKeos;
        }
        
        /// <summary>
        /// Łączna masa odpadów wydobytych ze składowiska [Mg]
        /// </summary>
        /// <value>Łączna masa odpadów wydobytych ze składowiska [Mg]</value>
        [DataMember(Name="wasteMassExcavatedSum", EmitDefaultValue=false)]
        public double? WasteMassExcavatedSum { get; set; }

        /// <summary>
        /// Karta keo
        /// </summary>
        /// <value>Karta keo</value>
        [DataMember(Name="keoDto", EmitDefaultValue=false)]
        public WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1KeoDto KeoDto { get; set; }

        /// <summary>
        /// Gets or Sets ExcavatedKeos
        /// </summary>
        [DataMember(Name="excavatedKeos", EmitDefaultValue=false)]
        public WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1PaginatedPageKeoExcavatedListItem ExcavatedKeos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse {\n");
            sb.Append("  WasteMassExcavatedSum: ").Append(WasteMassExcavatedSum).Append("\n");
            sb.Append("  KeoDto: ").Append(KeoDto).Append("\n");
            sb.Append("  ExcavatedKeos: ").Append(ExcavatedKeos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse);
        }

        /// <summary>
        /// Returns true if WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteRecordCardV1SearchKeoExcavatedResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.WasteMassExcavatedSum == input.WasteMassExcavatedSum ||
                    (this.WasteMassExcavatedSum != null &&
                    this.WasteMassExcavatedSum.Equals(input.WasteMassExcavatedSum))
                ) && 
                (
                    this.KeoDto == input.KeoDto ||
                    (this.KeoDto != null &&
                    this.KeoDto.Equals(input.KeoDto))
                ) && 
                (
                    this.ExcavatedKeos == input.ExcavatedKeos ||
                    (this.ExcavatedKeos != null &&
                    this.ExcavatedKeos.Equals(input.ExcavatedKeos))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WasteMassExcavatedSum != null)
                    hashCode = hashCode * 59 + this.WasteMassExcavatedSum.GetHashCode();
                if (this.KeoDto != null)
                    hashCode = hashCode * 59 + this.KeoDto.GetHashCode();
                if (this.ExcavatedKeos != null)
                    hashCode = hashCode * 59 + this.ExcavatedKeos.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
