/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse
    /// </summary>
    [DataContract]
    public partial class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse :  IEquatable<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse" /> class.
        /// </summary>
        /// <param name="initialVehiclesMass">Masa pojazdów [Mg].</param>
        /// <param name="initialVehiclesCount">Liczba pojazdów [szt.].</param>
        /// <param name="cardNumber">Numer karty.</param>
        /// <param name="wasteCode">Kod odpadu.</param>
        /// <param name="year">Rok kalendarzowy.</param>
        /// <param name="dismantleProducedWasteMass">Masa odpadów powstałych z demontażu pojazdów.</param>
        /// <param name="dismantleProducedReusablePartsMass">Masa przedmiotów wyposażenia i części przeznaczonych do ponownego użycia [Mg].</param>
        /// <param name="wasteCodeExtended">Kod ex.</param>
        /// <param name="wasteCodeExtendedDescription">Rodzaj odpadu ex.</param>
        /// <param name="hazardousWasteReclassification">Zmiana statusu odpadów niebezpiecznych na odpady inne niż niebezpieczne.</param>
        /// <param name="hazardousWasteReclassificationDescription">Rodzaj odpadu.</param>
        /// <param name="dismantleProducedWastes">dismantleProducedWastes.</param>
        public WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse(double? initialVehiclesMass = default(double?), int? initialVehiclesCount = default(int?), string cardNumber = default(string), string wasteCode = default(string), int? year = default(int?), double? dismantleProducedWasteMass = default(double?), double? dismantleProducedReusablePartsMass = default(double?), bool? wasteCodeExtended = default(bool?), string wasteCodeExtendedDescription = default(string), bool? hazardousWasteReclassification = default(bool?), string hazardousWasteReclassificationDescription = default(string), WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1PaginatedPageDismantleProducedWasteListItem dismantleProducedWastes = default(WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1PaginatedPageDismantleProducedWasteListItem))
        {
            this.InitialVehiclesMass = initialVehiclesMass;
            this.InitialVehiclesCount = initialVehiclesCount;
            this.CardNumber = cardNumber;
            this.WasteCode = wasteCode;
            this.Year = year;
            this.DismantleProducedWasteMass = dismantleProducedWasteMass;
            this.DismantleProducedReusablePartsMass = dismantleProducedReusablePartsMass;
            this.WasteCodeExtended = wasteCodeExtended;
            this.WasteCodeExtendedDescription = wasteCodeExtendedDescription;
            this.HazardousWasteReclassification = hazardousWasteReclassification;
            this.HazardousWasteReclassificationDescription = hazardousWasteReclassificationDescription;
            this.DismantleProducedWastes = dismantleProducedWastes;
        }
        
        /// <summary>
        /// Masa pojazdów [Mg]
        /// </summary>
        /// <value>Masa pojazdów [Mg]</value>
        [DataMember(Name="initialVehiclesMass", EmitDefaultValue=false)]
        public double? InitialVehiclesMass { get; set; }

        /// <summary>
        /// Liczba pojazdów [szt.]
        /// </summary>
        /// <value>Liczba pojazdów [szt.]</value>
        [DataMember(Name="initialVehiclesCount", EmitDefaultValue=false)]
        public int? InitialVehiclesCount { get; set; }

        /// <summary>
        /// Numer karty
        /// </summary>
        /// <value>Numer karty</value>
        [DataMember(Name="cardNumber", EmitDefaultValue=false)]
        public string CardNumber { get; set; }

        /// <summary>
        /// Kod odpadu
        /// </summary>
        /// <value>Kod odpadu</value>
        [DataMember(Name="wasteCode", EmitDefaultValue=false)]
        public string WasteCode { get; set; }

        /// <summary>
        /// Rok kalendarzowy
        /// </summary>
        /// <value>Rok kalendarzowy</value>
        [DataMember(Name="year", EmitDefaultValue=false)]
        public int? Year { get; set; }

        /// <summary>
        /// Masa odpadów powstałych z demontażu pojazdów
        /// </summary>
        /// <value>Masa odpadów powstałych z demontażu pojazdów</value>
        [DataMember(Name="dismantleProducedWasteMass", EmitDefaultValue=false)]
        public double? DismantleProducedWasteMass { get; set; }

        /// <summary>
        /// Masa przedmiotów wyposażenia i części przeznaczonych do ponownego użycia [Mg]
        /// </summary>
        /// <value>Masa przedmiotów wyposażenia i części przeznaczonych do ponownego użycia [Mg]</value>
        [DataMember(Name="dismantleProducedReusablePartsMass", EmitDefaultValue=false)]
        public double? DismantleProducedReusablePartsMass { get; set; }

        /// <summary>
        /// Kod ex
        /// </summary>
        /// <value>Kod ex</value>
        [DataMember(Name="wasteCodeExtended", EmitDefaultValue=false)]
        public bool? WasteCodeExtended { get; set; }

        /// <summary>
        /// Rodzaj odpadu ex
        /// </summary>
        /// <value>Rodzaj odpadu ex</value>
        [DataMember(Name="wasteCodeExtendedDescription", EmitDefaultValue=false)]
        public string WasteCodeExtendedDescription { get; set; }

        /// <summary>
        /// Zmiana statusu odpadów niebezpiecznych na odpady inne niż niebezpieczne
        /// </summary>
        /// <value>Zmiana statusu odpadów niebezpiecznych na odpady inne niż niebezpieczne</value>
        [DataMember(Name="hazardousWasteReclassification", EmitDefaultValue=false)]
        public bool? HazardousWasteReclassification { get; set; }

        /// <summary>
        /// Rodzaj odpadu
        /// </summary>
        /// <value>Rodzaj odpadu</value>
        [DataMember(Name="hazardousWasteReclassificationDescription", EmitDefaultValue=false)]
        public string HazardousWasteReclassificationDescription { get; set; }

        /// <summary>
        /// Gets or Sets DismantleProducedWastes
        /// </summary>
        [DataMember(Name="dismantleProducedWastes", EmitDefaultValue=false)]
        public WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1PaginatedPageDismantleProducedWasteListItem DismantleProducedWastes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse {\n");
            sb.Append("  InitialVehiclesMass: ").Append(InitialVehiclesMass).Append("\n");
            sb.Append("  InitialVehiclesCount: ").Append(InitialVehiclesCount).Append("\n");
            sb.Append("  CardNumber: ").Append(CardNumber).Append("\n");
            sb.Append("  WasteCode: ").Append(WasteCode).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  DismantleProducedWasteMass: ").Append(DismantleProducedWasteMass).Append("\n");
            sb.Append("  DismantleProducedReusablePartsMass: ").Append(DismantleProducedReusablePartsMass).Append("\n");
            sb.Append("  WasteCodeExtended: ").Append(WasteCodeExtended).Append("\n");
            sb.Append("  WasteCodeExtendedDescription: ").Append(WasteCodeExtendedDescription).Append("\n");
            sb.Append("  HazardousWasteReclassification: ").Append(HazardousWasteReclassification).Append("\n");
            sb.Append("  HazardousWasteReclassificationDescription: ").Append(HazardousWasteReclassificationDescription).Append("\n");
            sb.Append("  DismantleProducedWastes: ").Append(DismantleProducedWastes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse);
        }

        /// <summary>
        /// Returns true if WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProducedWastesResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InitialVehiclesMass == input.InitialVehiclesMass ||
                    (this.InitialVehiclesMass != null &&
                    this.InitialVehiclesMass.Equals(input.InitialVehiclesMass))
                ) && 
                (
                    this.InitialVehiclesCount == input.InitialVehiclesCount ||
                    (this.InitialVehiclesCount != null &&
                    this.InitialVehiclesCount.Equals(input.InitialVehiclesCount))
                ) && 
                (
                    this.CardNumber == input.CardNumber ||
                    (this.CardNumber != null &&
                    this.CardNumber.Equals(input.CardNumber))
                ) && 
                (
                    this.WasteCode == input.WasteCode ||
                    (this.WasteCode != null &&
                    this.WasteCode.Equals(input.WasteCode))
                ) && 
                (
                    this.Year == input.Year ||
                    (this.Year != null &&
                    this.Year.Equals(input.Year))
                ) && 
                (
                    this.DismantleProducedWasteMass == input.DismantleProducedWasteMass ||
                    (this.DismantleProducedWasteMass != null &&
                    this.DismantleProducedWasteMass.Equals(input.DismantleProducedWasteMass))
                ) && 
                (
                    this.DismantleProducedReusablePartsMass == input.DismantleProducedReusablePartsMass ||
                    (this.DismantleProducedReusablePartsMass != null &&
                    this.DismantleProducedReusablePartsMass.Equals(input.DismantleProducedReusablePartsMass))
                ) && 
                (
                    this.WasteCodeExtended == input.WasteCodeExtended ||
                    (this.WasteCodeExtended != null &&
                    this.WasteCodeExtended.Equals(input.WasteCodeExtended))
                ) && 
                (
                    this.WasteCodeExtendedDescription == input.WasteCodeExtendedDescription ||
                    (this.WasteCodeExtendedDescription != null &&
                    this.WasteCodeExtendedDescription.Equals(input.WasteCodeExtendedDescription))
                ) && 
                (
                    this.HazardousWasteReclassification == input.HazardousWasteReclassification ||
                    (this.HazardousWasteReclassification != null &&
                    this.HazardousWasteReclassification.Equals(input.HazardousWasteReclassification))
                ) && 
                (
                    this.HazardousWasteReclassificationDescription == input.HazardousWasteReclassificationDescription ||
                    (this.HazardousWasteReclassificationDescription != null &&
                    this.HazardousWasteReclassificationDescription.Equals(input.HazardousWasteReclassificationDescription))
                ) && 
                (
                    this.DismantleProducedWastes == input.DismantleProducedWastes ||
                    (this.DismantleProducedWastes != null &&
                    this.DismantleProducedWastes.Equals(input.DismantleProducedWastes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InitialVehiclesMass != null)
                    hashCode = hashCode * 59 + this.InitialVehiclesMass.GetHashCode();
                if (this.InitialVehiclesCount != null)
                    hashCode = hashCode * 59 + this.InitialVehiclesCount.GetHashCode();
                if (this.CardNumber != null)
                    hashCode = hashCode * 59 + this.CardNumber.GetHashCode();
                if (this.WasteCode != null)
                    hashCode = hashCode * 59 + this.WasteCode.GetHashCode();
                if (this.Year != null)
                    hashCode = hashCode * 59 + this.Year.GetHashCode();
                if (this.DismantleProducedWasteMass != null)
                    hashCode = hashCode * 59 + this.DismantleProducedWasteMass.GetHashCode();
                if (this.DismantleProducedReusablePartsMass != null)
                    hashCode = hashCode * 59 + this.DismantleProducedReusablePartsMass.GetHashCode();
                if (this.WasteCodeExtended != null)
                    hashCode = hashCode * 59 + this.WasteCodeExtended.GetHashCode();
                if (this.WasteCodeExtendedDescription != null)
                    hashCode = hashCode * 59 + this.WasteCodeExtendedDescription.GetHashCode();
                if (this.HazardousWasteReclassification != null)
                    hashCode = hashCode * 59 + this.HazardousWasteReclassification.GetHashCode();
                if (this.HazardousWasteReclassificationDescription != null)
                    hashCode = hashCode * 59 + this.HazardousWasteReclassificationDescription.GetHashCode();
                if (this.DismantleProducedWastes != null)
                    hashCode = hashCode * 59 + this.DismantleProducedWastes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
