/* 
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WasteCodeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WasteCodeApiTests
    {
        private WasteCodeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WasteCodeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WasteCodeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WasteCodeApi
            //Assert.IsInstanceOfType(typeof(WasteCodeApi), instance, "instance is a WasteCodeApi");
        }

        
        /// <summary>
        /// Test GetWasteCodes
        /// </summary>
        [Test]
        public void GetWasteCodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetWasteCodes();
            //Assert.IsInstanceOf<List<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteCodeV1WasteCodeDto>> (response, "response is List<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteCodeV1WasteCodeDto>");
        }
        
        /// <summary>
        /// Test SearchWasteCode
        /// </summary>
        [Test]
        public void SearchWasteCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteCodeV1SearchWasteCodeRequest request = null;
            //var response = instance.SearchWasteCode(request);
            //Assert.IsInstanceOf<List<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteCodeV1WasteCodeDto>> (response, "response is List<WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteCodeV1WasteCodeDto>");
        }
        
    }

}
